- name: install catalogue components
  hosts: catalogue
  become: yes
  tasks:
  - name: Setup NodeJS repos. Vendor is providing a script to setup the repos.
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"